'use client';

import { useMemo, useState } from 'react';
import { generateCSV, type Mode, type PeptideResult } from '@/lib/peptide';

const example = `TAT,YGRKKRRQRRR
candidate_1,KETWWETWWTEWSQPKKKRKV
candidate_2,RGDFFR`;
const badge = { Low: 'bg-rose-100 text-rose-700 ring-rose-200', Medium: 'bg-amber-100 text-amber-800 ring-amber-200', High: 'bg-emerald-100 text-emerald-700 ring-emerald-200' } as const;

export default function Home() {
  const [mode, setMode] = useState<Mode>('single'); const [input, setInput] = useState('TAT,YGRKKRRQRRR'); const [results, setResults] = useState<PeptideResult[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const top = results[0];
  async function analyze() { setLoading(true); setError(''); try { const res = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ input, mode }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error ?? 'Analysis failed'); setResults(data.results); } catch (err) { setError(err instanceof Error ? err.message : 'Analysis failed'); setResults([]); } finally { setLoading(false); } }
  const csvUrl = useMemo(() => results.length ? URL.createObjectURL(new Blob([generateCSV(results)], { type: 'text/csv;charset=utf-8;' })) : '', [results]);
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#dbeafe,transparent_35%),linear-gradient(#f8fafc,#eef2ff)]">
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-indigo-600">Research MVP</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-slate-950">BBB Peptide Score</h1><p className="mt-3 text-lg text-slate-600">Rapid in silico prioritization of BBB-penetrating peptide candidates</p></div><a className="text-sm font-semibold text-indigo-700 hover:text-indigo-900" href="/about">Method & disclaimer →</a></header>
      <div className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr]"><section className="rounded-3xl border border-white/80 bg-white/90 p-6 shadow-xl shadow-indigo-100"><div className="mb-5 flex rounded-2xl bg-slate-100 p-1">{(['single','batch'] as Mode[]).map((m) => <button key={m} onClick={() => setMode(m)} className={`flex-1 rounded-xl px-4 py-2 text-sm font-semibold capitalize ${mode === m ? 'bg-white text-indigo-700 shadow' : 'text-slate-600'}`}>{m}</button>)}</div><label className="text-sm font-semibold text-slate-700" htmlFor="peptides">Peptide input</label><textarea id="peptides" value={input} onChange={(e) => setInput(e.target.value)} placeholder={example} className="mt-2 h-64 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 font-mono text-sm outline-none ring-indigo-200 transition focus:border-indigo-400 focus:ring-4" /><p className="mt-3 text-xs text-slate-500">Accepted: plain sequence or name,sequence. Lowercase is normalized and spaces are removed.</p>{error && <p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><button onClick={analyze} disabled={loading} className="rounded-2xl bg-indigo-600 px-5 py-3 font-semibold text-white shadow-lg shadow-indigo-200 hover:bg-indigo-700 disabled:opacity-60">{loading ? 'Analyzing…' : 'Analyze'}</button><button onClick={() => { setInput(''); setResults([]); setError(''); }} className="rounded-2xl border border-slate-200 bg-white px-5 py-3 font-semibold text-slate-700 hover:bg-slate-50">Clear</button>{results.length > 0 && <a download="bbb-peptide-score.csv" href={csvUrl} className="rounded-2xl border border-indigo-200 bg-indigo-50 px-5 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Download CSV</a>}</div></section>
      <section className="space-y-6">{!top ? <div className="rounded-3xl border border-dashed border-indigo-200 bg-white/70 p-10 text-center text-slate-500">Run an analysis to see score, metrics, warnings, interpretation, and validation suggestions.</div> : mode === 'single' ? <SingleResult result={top} /> : <BatchResults results={results} />}</section></div>
    </section><Disclaimer /></main>;
}
function Pill({ value }: { value: 'Low' | 'Medium' | 'High' }) { return <span className={`rounded-full px-3 py-1 text-xs font-bold ring-1 ${badge[value]}`}>{value}</span>; }
function SingleResult({ result }: { result: PeptideResult }) { const m = result.metrics; return <article className="rounded-3xl border bg-white p-6 shadow-xl shadow-indigo-100"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-slate-500">{result.name} · <span className="font-mono">{result.sequence}</span></p><h2 className="mt-2 text-3xl font-bold text-slate-950">BBB Penetration Score</h2></div><div className="text-right"><div className="text-6xl font-black text-indigo-600">{result.bbbScore}</div><Pill value={result.predictionClass} /></div></div><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Confidence', result.confidence], ['Length', m.length], ['MW', m.molecularWeight], ['Net charge', m.netChargePh74], ['Basic frac.', m.basicFraction], ['Hydrophobic', m.hydrophobicFraction], ['GRAVY', m.gravy], ['CPP-like', m.cppLikeScore]].map(([k,v]) => <div key={k} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase text-slate-500">{k}</p><p className="mt-1 text-xl font-bold text-slate-900">{v}</p></div>)}</div><Info result={result} /></article>; }
function Info({ result }: { result: PeptideResult }) { return <div className="mt-6 grid gap-5 md:grid-cols-3"><Panel title="Warnings" items={result.warnings.length ? result.warnings : ['No major heuristic warnings.']} warn={result.warnings.length > 0} /><Panel title="Interpretation" items={result.interpretation} /><Panel title="Suggested validation" items={result.validationSuggestions} /></div>; }
function Panel({ title, items, warn = false }: { title: string; items: string[]; warn?: boolean }) { return <div><h3 className="font-bold text-slate-900">{title}</h3><ul className="mt-2 space-y-2 text-sm text-slate-600">{items.map((item) => <li key={item} className={`rounded-xl p-3 ${warn ? 'bg-amber-50 text-amber-800' : 'bg-slate-50'}`}>{item}</li>)}</ul></div>; }
function BatchResults({ results }: { results: PeptideResult[] }) { return <div className="rounded-3xl border bg-white p-6 shadow-xl shadow-indigo-100"><h2 className="text-2xl font-bold">Ranked batch results</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{['Rank','Name','Sequence','Score','Class','Confidence','Length','Warnings'].map((h) => <th className="px-3 py-2" key={h}>{h}</th>)}</tr></thead><tbody>{results.map((r,i) => <tr key={`${r.name}-${i}`} className="border-t"><td className="px-3 py-3 font-bold">{i+1}</td><td className="px-3 py-3 font-semibold">{r.name}</td><td className="px-3 py-3 font-mono text-xs">{r.sequence}</td><td className="px-3 py-3 text-xl font-black text-indigo-600">{r.bbbScore}</td><td className="px-3 py-3"><Pill value={r.predictionClass} /></td><td className="px-3 py-3">{r.confidence}</td><td className="px-3 py-3">{r.metrics.length}</td><td className="px-3 py-3 text-amber-700">{r.warnings.join('; ') || '—'}</td></tr>)}</tbody></table></div>{results[0] && <Info result={results[0]} />}</div>; }
function Disclaimer() { return <footer className="mx-auto max-w-7xl px-4 pb-8 sm:px-6 lg:px-8"><div className="rounded-2xl border border-indigo-100 bg-white/80 p-4 text-sm text-slate-600"><strong className="text-slate-900">Disclaimer:</strong> This tool provides an in silico prioritization score for research use only. It does not prove BBB penetration, brain exposure, pharmacokinetics, safety, or therapeutic efficacy. Experimental validation is required.</div></footer>; }
